"""App icon: generated by build/make_icon.py, shipped as assets/icon.ico, shown on the window."""
from __future__ import annotations

from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parents[1]


def test_make_icon_writes_multi_size_ico_and_png(tmp_path: Path):
    from build.make_icon import ICO_SIZES, make_icon

    ico, png = make_icon(tmp_path / "out")

    assert ico.exists() and png.exists()
    with Image.open(ico) as im:
        assert im.format == "ICO"
        # every size Windows asks for (taskbar 32/48, Explorer 256, title bar 16) is present
        assert set(im.info["sizes"]) == {(s, s) for s in ICO_SIZES}
    with Image.open(png) as im:
        assert im.size == (256, 256)
        assert im.mode == "RGBA"


def test_generated_icon_is_not_blank(tmp_path: Path):
    from build.make_icon import make_icon

    _, png = make_icon(tmp_path / "out")
    with Image.open(png) as im:
        colors = im.getcolors(maxcolors=1 << 20)
    assert colors is not None and len(colors) > 50   # a drawing, not a flat square


def test_repo_ships_the_icon_files():
    assert (ROOT / "assets" / "icon.ico").is_file()
    assert (ROOT / "assets" / "icon.png").is_file()


def test_app_icon_resolves_to_the_shipped_file():
    from ui.resources import app_icon_path

    assert app_icon_path() == ROOT / "assets" / "icon.ico"


def test_main_window_has_the_app_icon(qtbot, tmp_path: Path):
    from PySide6.QtCore import QSettings

    from core.thumbnails import ThumbnailCache
    from ui.main_window import MainWindow

    settings = QSettings(str(tmp_path / "settings.ini"), QSettings.Format.IniFormat)
    w = MainWindow(thumb_cache=ThumbnailCache(tmp_path / "cache"), settings=settings)
    qtbot.addWidget(w)
    assert not w.windowIcon().isNull()
